import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React from 'react';
import { X, Shield, FileText } from 'lucide-react';
const BaseModal = ({ isOpen, onClose, title, icon: Icon, content }) => {
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-slate-900/50 backdrop-blur-sm flex items-center justify-center z-[60] p-4", children: _jsxs("div", { className: "bg-white dark:bg-slate-800 rounded-xl max-w-2xl w-full max-h-[80vh] flex flex-col shadow-2xl border border-slate-200 dark:border-slate-700", children: [_jsxs("div", { className: "flex items-center justify-between p-6 border-b border-slate-200 dark:border-slate-700", children: [_jsxs("div", { className: "flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white", children: [_jsx(Icon, { className: "w-5 h-5" }), " ", title] }), _jsx("button", { onClick: onClose, children: _jsx(X, { className: "w-5 h-5 text-slate-500" }) })] }), _jsx("div", { className: "p-6 overflow-y-auto text-sm text-slate-600 dark:text-slate-300 leading-relaxed space-y-4", children: content })] }) }));
};
export const TermsModal = ({ isOpen, onClose }) => (_jsx(BaseModal, { isOpen: isOpen, onClose: onClose, title: "Terms of Service", icon: FileText, content: _jsxs(_Fragment, { children: [_jsxs("p", { children: [_jsx("strong", { children: "1. Introduction" }), _jsx("br", {}), "Welcome to Netolyte. By accessing our website and using our services, you agree to comply with these terms."] }), _jsxs("p", { children: [_jsx("strong", { children: "2. Services" }), _jsx("br", {}), "Netolyte provides business-to-business lead generation services using artificial intelligence."] }), _jsxs("p", { children: [_jsx("strong", { children: "3. Usage Limits" }), _jsx("br", {}), "Users are limited to the number of credits purchased. Automated scraping of our platform is prohibited."] }), _jsxs("p", { children: [_jsx("strong", { children: "4. Data Accuracy" }), _jsx("br", {}), "While we strive for accuracy, AI-generated data may verify over time. We do not guarantee 100% accuracy of contact information."] }), _jsxs("p", { children: [_jsx("strong", { children: "5. Refund Policy" }), _jsx("br", {}), "Refunds are available within 30 days of purchase if no credits have been used."] })] }) }));
export const PrivacyModal = ({ isOpen, onClose }) => (_jsx(BaseModal, { isOpen: isOpen, onClose: onClose, title: "Privacy Policy", icon: Shield, content: _jsxs(_Fragment, { children: [_jsxs("p", { children: [_jsx("strong", { children: "1. Data Collection" }), _jsx("br", {}), "We collect email addresses and usage data to improve our services and process payments."] }), _jsxs("p", { children: [_jsx("strong", { children: "2. Data Usage" }), _jsx("br", {}), "Your search queries are processed by Google Gemini AI. We do not sell your personal search history to third parties."] }), _jsxs("p", { children: [_jsx("strong", { children: "3. Security" }), _jsx("br", {}), "We use industry-standard encryption to protect your account information and payment details."] }), _jsxs("p", { children: [_jsx("strong", { children: "4. Cookies" }), _jsx("br", {}), "We use cookies to maintain your session and preference settings."] })] }) }));
